<?php

namespace Database\Seeders;

use App\Models\Characteristic;
use Illuminate\Database\Seeder;

class CharacteristicsSeeder extends Seeder
{
    public function run(): void
    {
        $caracteristics = [
            ['name' => 'Durata della batteria','category_id' => '1'],
            ['name' => 'Qualità della fotocamera','category_id' => '1'],
            ['name' => 'Capacità di memoria','category_id' => '1'],
            ['name' => 'Velocità del processore','category_id' => '1'],
            ['name' => 'Sistema operativo','category_id' => '1'],
            ['name' => 'Compatibilità con accessori','category_id' => '1'],
            ['name' => 'Qualità del display','category_id' => '1'],
            ['name' => 'Velocità del processore','category_id' => '2'],
            ['name' => 'Quantità di RAM','category_id' => '2'],
            ['name' => 'Capacità di archiviazione','category_id' => '2'],
            ['name' => 'Qualità del display','category_id' => '2'],
            ['name' => 'Durata della batteria','category_id' => '2'],
            ['name' => 'Sistema operativo','category_id' => '2'],
            ['name' => 'Portabilità','category_id' => '2'],
            ['name' => 'Risoluzione del display','category_id' => '3'],
            ['name' => 'Dimensione dello schermo','category_id' => '3'],
            ['name' => 'Qualità del suono','category_id' => '3'],
            ['name' => 'Connettività','category_id' => '3'],
            ['name' => 'Funzioni Smart TV','category_id' => '3'],
            ['name' => 'Consumo energetico','category_id' => '3'],
            ['name' => 'Tecnologia del display','category_id' => '3'],
            ['name' => 'Risoluzione dell\'immagine','category_id' => '4'],
            ['name' => 'Stabilizzazione dell\'immagine','category_id' => '4'],
            ['name' => 'Dimensione del sensore','category_id' => '4'],
            ['name' => 'Varietà di lenti disponibili','category_id' => '4'],
            ['name' => 'Durata della batteria','category_id' => '4'],
            ['name' => 'Connettività ','category_id' => '4'],
            ['name' => 'Facilità d\'uso','category_id' => '4'],
            ['name' => 'Efficienza energetica','category_id' => '5'],
            ['name' => 'Capacità ','category_id' => '5'],
            ['name' => 'Funzioni speciali','category_id' => '5'],
            ['name' => 'Durata e qualità dei materiali','category_id' => '5'],
            ['name' => 'Livello di rumore','category_id' => '5'],
            ['name' => 'Facilità di manutenzione','category_id' => '5'],
            ['name' => 'Sicurezza','category_id' => '5'],
            ['name' => 'Qualità del tessuto','category_id' => '6'],
            ['name' => 'Vestibilità','category_id' => '6'],
            ['name' => 'Design e stile','category_id' => '6'],
            ['name' => 'Durabilità','category_id' => '6'],
            ['name' => 'Comfort','category_id' => '6'],
            ['name' => 'Facilità di manutenzione','category_id' => '6'],
            ['name' => 'Qualità del tessuto','category_id' => '7'],
            ['name' => 'Vestibilità','category_id' => '7'],
            ['name' => 'Design e stile','category_id' => '7'],
            ['name' => 'Durabilità','category_id' => '7'],
            ['name' => 'Comfort','category_id' => '7'],
            ['name' => 'Facilità di manutenzione','category_id' => '7'],
            ['name' => 'Qualità del tessuto','category_id' => '8'],
            ['name' => 'Vestibilità','category_id' => '8'],
            ['name' => 'Design e stile','category_id' => '8'],
            ['name' => 'Durabilità','category_id' => '8'],
            ['name' => 'Comfort','category_id' => '8'],
            ['name' => 'Facilità di manutenzione','category_id' => '8'],
            ['name' => 'Comfort','category_id' => '9'],
            ['name' => 'Qualità dei materiali','category_id' => '9'],
            ['name' => 'Design e stile','category_id' => '9'],
            ['name' => 'Durabilità','category_id' => '9'],
            ['name' => 'Adattabilità','category_id' => '9'],
            ['name' => 'Tipo di suola','category_id' => '9'],
            ['name' => 'Qualità dei materiali','category_id' => '10'],
            ['name' => 'Design e stile','category_id' => '10'],
            ['name' => 'Versatilità','category_id' => '10'],
            ['name' => 'Durabilità','category_id' => '10'],
            ['name' => 'Facilità di manutenzione','category_id' => '10'],
            ['name' => 'Brand/reputazione','category_id' => '10'],
            ['name' => 'Qualità dei materiali','category_id' => '11'],
            ['name' => 'Design e stile','category_id' => '11'],
            ['name' => 'Comfort','category_id' => '11'],
            ['name' => 'Durabilità','category_id' => '11'],
            ['name' => 'Facilità di manutenzione','category_id' => '11'],
            ['name' => 'Facilità di montaggio','category_id' => '11'],
            ['name' => 'Design e stile','category_id' => '12'],
            ['name' => 'Qualità dei materiali','category_id' => '12'],
            ['name' => 'Durabilità','category_id' => '12'],
            ['name' => 'Facilità di pulizia','category_id' => '12'],
            ['name' => 'Versatilità','category_id' => '12'],
            ['name' => 'Brand/reputazione','category_id' => '12'],
            ['name' => 'Efficienza energetica','category_id' => '13'],
            ['name' => 'Funzionalità e caratteristiche speciali','category_id' => '13'],
            ['name' => 'Durabilità','category_id' => '13'],
            ['name' => 'Facilità d\'uso','category_id' => '13'],
            ['name' => 'Livello di rumore','category_id' => '13'],
            ['name' => 'Facilità di manutenzione','category_id' => '13'],
            ['name' => 'Durabilità degli attrezzi','category_id' => '14'],
            ['name' => 'Facilità d\'uso','category_id' => '14'],
            ['name' => 'Ergonomia','category_id' => '14'],
            ['name' => 'Qualità dei materiali','category_id' => '14'],
            ['name' => 'Versatilità degli attrezzi','category_id' => '14'],
            ['name' => 'Reputazione del brand','category_id' => '14'],
            ['name' => 'Qualità dei materiali','category_id' => '15'],
            ['name' => 'Funzionalità','category_id' => '15'],
            ['name' => 'Durabilità','category_id' => '15'],
            ['name' => 'Facilità di pulizia','category_id' => '15'],
            ['name' => 'Efficienza energetica','category_id' => '15'],
            ['name' => 'Design e stile','category_id' => '15'],
            ['name' => 'Ingredienti','category_id' => '16'],
            ['name' => 'Efficacia','category_id' => '16'],
            ['name' => 'Adattabilità a diversi tipi di pelle','category_id' => '16'],
            ['name' => 'Facilità d\'uso','category_id' => '16'],
            ['name' => 'Brand/reputazione','category_id' => '16'],
            ['name' => 'Effetti collaterali (ipotetici)','category_id' => '16'],
            ['name' => 'Qualità degli ingredienti','category_id' => '17'],
            ['name' => 'Durabilità','category_id' => '17'],
            ['name' => 'Facile applicazione','category_id' => '17'],
            ['name' => 'Compatibilità con diversi tipi di pelle','category_id' => '17'],
            ['name' => 'Gamma di colori','category_id' => '17'],
            ['name' => 'Brand/reputazione','category_id' => '17'],
            ['name' => 'Fragranza','category_id' => '18'],
            ['name' => 'Durata della fragranza','category_id' => '18'],
            ['name' => 'Ingredienti','category_id' => '18'],
            ['name' => 'Design della bottiglia','category_id' => '18'],
            ['name' => 'Adattabilità alla pelle','category_id' => '18'],
            ['name' => 'Brand/reputazione','category_id' => '18'],
            ['name' => 'Efficacia','category_id' => '19'],
            ['name' => 'Ingredienti','category_id' => '19'],
            ['name' => 'Facilità d\'uso','category_id' => '19'],
            ['name' => 'Dosaggio','category_id' => '19'],
            ['name' => 'Effetti collaterali','category_id' => '19'],
            ['name' => 'Brand/reputazione','category_id' => '19'],
            ['name' => 'Funzionalità','category_id' => '20'],
            ['name' => 'Durabilità','category_id' => '20'],
            ['name' => 'Facilità d\'uso','category_id' => '20'],
            ['name' => 'Design','category_id' => '20'],
            ['name' => 'Efficienza energetica','category_id' => '20'],
            ['name' => 'Brand/reputazione','category_id' => '20'],
            ['name' => 'Comfort','category_id' => '21'],
            ['name' => 'Qualità del tessuto','category_id' => '21'],
            ['name' => 'Traspirabilità','category_id' => '21'],
            ['name' => 'Durabilità','category_id' => '21'],
            ['name' => 'Design e stile','category_id' => '21'],
            ['name' => 'Facilità di manutenzione','category_id' => '21'],
            ['name' => 'Funzionalità','category_id' => '22'],
            ['name' => 'Durabilità','category_id' => '22'],
            ['name' => 'Facilità d\'uso','category_id' => '22'],
            ['name' => 'Dimensioni e ingombro','category_id' => '22'],
            ['name' => 'Versatilità','category_id' => '22'],
            ['name' => 'Brand/reputazione','category_id' => '22'],
            ['name' => 'Funzionalità','category_id' => '23'],
            ['name' => 'Durabilità','category_id' => '23'],
            ['name' => 'Facilità d\'uso','category_id' => '23'],
            ['name' => 'Qualità dei materiali','category_id' => '23'],
            ['name' => 'Adattabilità','category_id' => '23'],
            ['name' => 'Brand/reputazione','category_id' => '23'],
            ['name' => 'Durabilità','category_id' => '24'],
            ['name' => 'Resistenza agli agenti atmosferici','category_id' => '24'],
            ['name' => 'Peso e portabilità','category_id' => '24'],
            ['name' => 'Funzionalità','category_id' => '24'],
            ['name' => 'Facilità d\'uso','category_id' => '24'],
            ['name' => 'Brand/reputazione','category_id' => '24'],
            ['name' => 'Sicurezza','category_id' => '25'],
            ['name' => 'Durabilità','category_id' => '25'],
            ['name' => 'Educatività','category_id' => '25'],
            ['name' => 'Divertimento','category_id' => '25'],
            ['name' => 'Design e colori','category_id' => '25'],
            ['name' => 'Adattabilità all\'età','category_id' => '25'],
            ['name' => 'Freschezza','category_id' => '26'],
            ['name' => 'Qualità degli ingredienti','category_id' => '26'],
            ['name' => 'Origine','category_id' => '26'],
            ['name' => 'Confezionamento','category_id' => '26'],
            ['name' => 'Valori nutrizionali','category_id' => '26'],
            ['name' => 'Sapore','category_id' => '26'],
            ['name' => 'Durata di conservazione','category_id' => '27'],
            ['name' => 'Qualità degli ingredienti','category_id' => '27'],
            ['name' => 'Confezionamento','category_id' => '27'],
            ['name' => 'Valori nutrizionali','category_id' => '27'],
            ['name' => 'Facilità d\'uso','category_id' => '27'],
            ['name' => 'Sapore','category_id' => '27'],
            ['name' => 'Sapore','category_id' => '28'],
            ['name' => 'Gradazione alcolica','category_id' => '28'],
            ['name' => 'Qualità degli ingredienti','category_id' => '28'],
            ['name' => 'Origine','category_id' => '28'],
            ['name' => 'Confezionamento','category_id' => '28'],
            ['name' => 'Brand/reputazione','category_id' => '28'],
            ['name' => 'Sapore','category_id' => '29'],
            ['name' => 'Valori nutrizionali','category_id' => '29'],
            ['name' => 'Qualità degli ingredienti','category_id' => '29'],
            ['name' => 'Confezionamento','category_id' => '29'],
            ['name' => 'Freschezza','category_id' => '29'],
            ['name' => 'Varietà di gusti','category_id' => '29'],
            ['name' => 'Certificazioni biologiche','category_id' => '30'],
            ['name' => 'Ingredienti','category_id' => '30'],
            ['name' => 'Valori nutrizionali','category_id' => '30'],
            ['name' => 'Sapore','category_id' => '30'],
            ['name' => 'Confezionamento','category_id' => '30'],
            ['name' => 'Origine','category_id' => '30'],
            ['name' => 'Qualità della scrittura','category_id' => '31'],
            ['name' => 'Genere','category_id' => '31'],
            ['name' => 'Formato','category_id' => '31'],
            ['name' => 'Autore','category_id' => '31'],
            ['name' => 'Recensioni','category_id' => '31'],
            ['name' => 'Edizione','category_id' => '31'],
            ['name' => 'Qualità del video','category_id' => '32'],
            ['name' => 'Trama','category_id' => '32'],
            ['name' => 'Cast','category_id' => '32'],
            ['name' => 'Durata','category_id' => '32'],
            ['name' => 'Recensioni','category_id' => '32'],
            ['name' => 'Formato','category_id' => '32'],
            ['name' => 'Qualità del suono','category_id' => '33'],
            ['name' => 'Artista','category_id' => '33'],
            ['name' => 'Genere','category_id' => '33'],
            ['name' => 'Numero di tracce','category_id' => '33'],
            ['name' => 'Recensioni','category_id' => '33'],
            ['name' => 'Formato','category_id' => '33'],
            ['name' => 'Qualità della narrazione','category_id' => '34'],
            ['name' => 'Autore','category_id' => '34'],
            ['name' => 'Facilità di download/accesso','category_id' => '34'],
            ['name' => 'Formato','category_id' => '34'],
            ['name' => 'Recensioni','category_id' => '34'],
            ['name' => 'Durata','category_id' => '34'],
            ['name' => 'Qualità del suono','category_id' => '35'],
            ['name' => 'Marca','category_id' => '35'],
            ['name' => 'Durabilità','category_id' => '35'],
            ['name' => 'Facilità d\'uso','category_id' => '35'],
            ['name' => 'Materiali','category_id' => '35'],
            ['name' => 'Recensioni','category_id' => '35'],
            ['name' => 'Funzionalità','category_id' => '36'],
            ['name' => 'Durabilità','category_id' => '36'],
            ['name' => 'Facilità di installazione','category_id' => '36'],
            ['name' => 'Compatibilità con il veicolo','category_id' => '36'],
            ['name' => 'Qualità dei materiali','category_id' => '36'],
            ['name' => 'Brand/reputazione','category_id' => '36'],
            ['name' => 'Funzionalità','category_id' => '37'],
            ['name' => 'Durabilità','category_id' => '37'],
            ['name' => 'Facilità di installazione','category_id' => '37'],
            ['name' => 'Compatibilità con il veicolo','category_id' => '37'],
            ['name' => 'Qualità dei materiali','category_id' => '37'],
            ['name' => 'Brand/reputazione','category_id' => '37'],
            ['name' => 'Compatibilità con il veicolo','category_id' => '38'],
            ['name' => 'Qualità dei materiali','category_id' => '38'],
            ['name' => 'Durabilità','category_id' => '38'],
            ['name' => 'Facilità di installazione','category_id' => '38'],
            ['name' => 'Disponibilità','category_id' => '38'],
            ['name' => 'Brand/reputazione','category_id' => '38'],
            ['name' => 'Funzionalità','category_id' => '39'],
            ['name' => 'Facilità di installazione','category_id' => '39'],
            ['name' => 'Durabilità','category_id' => '39'],
            ['name' => 'Compatibilità con il veicolo','category_id' => '39'],
            ['name' => 'Qualità del suono','category_id' => '39'],
            ['name' => 'Brand/reputazione','category_id' => '39'],
            ['name' => 'Efficacia','category_id' => '40'],
            ['name' => 'Facilità d\'uso','category_id' => '40'],
            ['name' => 'Durabilità','category_id' => '40'],
            ['name' => 'Qualità degli ingredienti/materiali','category_id' => '40'],
            ['name' => 'Sicurezza','category_id' => '40'],
            ['name' => 'Brand/reputazione','category_id' => '40'],
            ['name' => 'Design e stile','category_id' => '41'],
            ['name' => 'Qualità dei materiali','category_id' => '41'],
            ['name' => 'Durabilità','category_id' => '41'],
            ['name' => 'Brand/reputazione','category_id' => '41'],
            ['name' => 'Certificazioni','category_id' => '41'],
            ['name' => 'Occasioni d\'uso','category_id' => '41'],
            ['name' => 'Design e stile','category_id' => '42'],
            ['name' => 'Qualità dei materiali','category_id' => '42'],
            ['name' => 'Durabilità','category_id' => '42'],
            ['name' => 'Brand/reputazione','category_id' => '42'],
            ['name' => 'Certificazioni','category_id' => '42'],
            ['name' => 'Occasioni d\'uso','category_id' => '42'],
            ['name' => 'Design e stile','category_id' => '43'],
            ['name' => 'Precisione del movimento','category_id' => '43'],
            ['name' => 'Qualità dei materiali','category_id' => '43'],
            ['name' => 'Durabilità','category_id' => '43'],
            ['name' => 'Brand/reputazione','category_id' => '43'],
            ['name' => 'Funzionalità aggiuntive','category_id' => '43'],
            ['name' => 'Design e stile','category_id' => '44'],
            ['name' => 'Precisione del movimento','category_id' => '44'],
            ['name' => 'Qualità dei materiali','category_id' => '44'],
            ['name' => 'Durabilità','category_id' => '44'],
            ['name' => 'Brand/reputazione','category_id' => '44'],
            ['name' => 'Funzionalità aggiuntive','category_id' => '44'],
            ['name' => 'Design e stile','category_id' => '45'],
            ['name' => 'Qualità dei materiali','category_id' => '45'],
            ['name' => 'Certificazioni','category_id' => '45'],
            ['name' => 'Durabilità','category_id' => '45'],
            ['name' => 'Brand/reputazione','category_id' => '45'],
            ['name' => 'Significato/simbolismo','category_id' => '45'],
            ['name' => 'Valore educativo','category_id' => '46'],
            ['name' => 'Sicurezza','category_id' => '46'],
            ['name' => 'Durabilità','category_id' => '46'],
            ['name' => 'Divertimento','category_id' => '46'],
            ['name' => 'Età consigliata','category_id' => '46'],
            ['name' => 'Design e colori','category_id' => '46'],
            ['name' => 'Sicurezza','category_id' => '47'],
            ['name' => 'Morbidezza','category_id' => '47'],
            ['name' => 'Durabilità','category_id' => '47'],
            ['name' => 'Dimensioni','category_id' => '47'],
            ['name' => 'Facilità di pulizia','category_id' => '47'],
            ['name' => 'Design e colori','category_id' => '47'],
            ['name' => 'Sicurezza','category_id' => '48'],
            ['name' => 'Funzionalità','category_id' => '48'],
            ['name' => 'Durabilità','category_id' => '48'],
            ['name' => 'Facilità d\'uso','category_id' => '48'],
            ['name' => 'Materiali','category_id' => '48'],
            ['name' => 'Brand/reputazione','category_id' => '48'],
            ['name' => 'Sicurezza','category_id' => '49'],
            ['name' => 'Facilità d\'uso','category_id' => '49'],
            ['name' => 'Durabilità','category_id' => '49'],
            ['name' => 'Comfort','category_id' => '49'],
            ['name' => 'Peso e portabilità','category_id' => '49'],
            ['name' => 'Brand/reputazione','category_id' => '49'],
            ['name' => 'Sicurezza','category_id' => '50'],
            ['name' => 'Efficienza','category_id' => '50'],
            ['name' => 'Facilità d\'uso','category_id' => '50'],
            ['name' => 'Ingredienti/materiali','category_id' => '50'],
            ['name' => 'Durabilità','category_id' => '50'],
            ['name' => 'Brand/reputazione','category_id' => '50'],
            ['name' => 'Marca','category_id' => '50'],
            ['name' => 'Funzionalità','category_id' => '51'],
            ['name' => 'Qualità','category_id' => '51'],
            ['name' => 'Durata e resistenza','category_id' => '51'],
            ['name' => 'Marca','category_id' => '51'],
            ['name' => 'Facilità d\'uso','category_id' => '51'],
            ['name' => 'Compatibilità','category_id' => '51'],
            ['name' => 'Materiale','category_id' => '52'],
            ['name' => 'Comfort','category_id' => '52'],
            ['name' => 'Design','category_id' => '52'],
            ['name' => 'Durata e resistenza','category_id' => '52'],
            ['name' => 'Facilità di montaggio','category_id' => '52'],
            ['name' => 'Ergonomia','category_id' => '52'],
            ['name' => 'Funzionalità','category_id' => '53'],
            ['name' => 'Compatibilità','category_id' => '53'],
            ['name' => 'Durata e resistenza','category_id' => '53'],
            ['name' => 'Marca','category_id' => '53'],
            ['name' => 'Facilità d\'uso','category_id' => '53'],
            ['name' => 'Qualità','category_id' => '53'],
            ['name' => 'Qualità','category_id' => '54'],
            ['name' => 'Durata','category_id' => '54'],
            ['name' => 'Marca','category_id' => '54'],
            ['name' => 'Tipo','category_id' => '54'],
            ['name' => 'Funzionalità','category_id' => '54'],
            ['name' => 'Compatibilità','category_id' => '54'],
            ['name' => 'Funzionalità','category_id' => '55'],
            ['name' => 'Qualità','category_id' => '55'],
            ['name' => 'Design','category_id' => '55'],
            ['name' => 'Durata e resistenza','category_id' => '55'],
            ['name' => 'Marca','category_id' => '55'],
            ['name' => 'Facilità d\'uso','category_id' => '55'],
            ['name' => 'Materiale','category_id' => '56'],
            ['name' => 'Dimensioni e capacità','category_id' => '56'],
            ['name' => 'Durata e resistenza','category_id' => '56'],
            ['name' => 'Peso','category_id' => '56'],
            ['name' => 'Facilità di trasporto','category_id' => '56'],
            ['name' => 'Sicurezza','category_id' => '56'],
            ['name' => 'Design','category_id' => '56'],
            ['name' => 'Materiale','category_id' => '57'],
            ['name' => 'Dimensioni e capacità','category_id' => '57'],
            ['name' => 'Comfort','category_id' => '57'],
            ['name' => 'Durata e resistenza','category_id' => '57'],
            ['name' => 'Peso','category_id' => '57'],
            ['name' => 'Compartimenti e tasche','category_id' => '57'],
            ['name' => 'Design','category_id' => '57'],
            ['name' => 'Funzionalità','category_id' => '58'],
            ['name' => 'Peso e portabilità','category_id' => '58'],
            ['name' => 'Durata e resistenza','category_id' => '58'],
            ['name' => 'Sicurezza','category_id' => '58'],
            ['name' => 'Facilità d\'uso','category_id' => '58'],
            ['name' => 'Design','category_id' => '58'],
            ['name' => 'Accuratezza delle informazioni','category_id' => '59'],
            ['name' => 'Copertura delle destinazioni','category_id' => '59'],
            ['name' => 'Facilità d\'uso','category_id' => '59'],
            ['name' => 'Qualità delle immagini','category_id' => '59'],
            ['name' => 'Autore','category_id' => '59'],
            ['name' => 'Recensioni','category_id' => '59'],
            ['name' => 'Durata e resistenza','category_id' => '60'],
            ['name' => 'Peso e portabilità','category_id' => '60'],
            ['name' => 'Funzionalità','category_id' => '60'],
            ['name' => 'Materiale','category_id' => '60'],
            ['name' => 'Sicurezza','category_id' => '60'],
            ['name' => 'Facilità di montaggio e smontaggio','category_id' => '60'],
        ];

        foreach($caracteristics as $caracteristic){
            Characteristic::create([
                'name' => $caracteristic['name'],
                'category_id' => $caracteristic['category_id'],
            ]);
        }
    }
}
